#!/bin/bash

# Argument substitution done by PiKrellCam before running this script:
#   $I - install directory full path
#   $P - the fifo command file full path
#   $G - log file configured in ~/.pikrellcam/pikrellcam.conf.
#   $Z - pikrellcam version number.
# 

INSTALL_DIR=$1
FIFO=$2
LOG_FILE=$3
CURRENT_VERSION=$4

WWW_CONFIG=$INSTALL_DIR/www/config.php

# Define the tag once
TAG="pikrellcam"

# Helper function
log_info() {
	logger  -t "$TAG"-i -p user.info "$1"
}


cd $INSTALL_DIR

CURRENT_COMMIT=`git log -1 --format=%cd`

# echo "inform \"inform string\" row justify font xs ys" > $FIFO
# row: 0 - 9  of the inform area.  10 large font rows may not fit.
# justify: 4=left  3=center 2=left at x  1=center at x  0=right <0=right in field
# font: 0=normal  1=large
# xs, ys offsets in pixels
#

echo "inform \"PiKrellCam V$CURRENT_VERSION current commit:\" 1 3 1" > $FIFO
echo "inform \"$CURRENT_COMMIT\" 2 3 1" > $FIFO
echo "inform \"Checking for upgrade...\" 3 3 1" > $FIFO

git fetch  &> /dev/null

log_info "Starte Git-Reset auf origin/master..."

# Führe den Reset aus und fange Fehlermeldungen ab
GIT_OUT=$(git reset --hard origin/master 2>&1)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    log_info "Git Success: $GIT_OUT"
else
    # Falls Git einen Fehler wirft, jede Zeile einzeln loggen
    echo "$GIT_OUT" | while read -r line; do
        log_info "Git ERROR (Code $EXIT_CODE): $line"
    done
fi

NEW_VERSION=`./pikrellcam --version`
NEW_COMMIT=`git log -1 --format=%cd`
COMMIT_SUBJECT=`git log -1 --format=%s`

echo "inform \" \" 3 3 1" > $FIFO
if [ "$NEW_COMMIT" != "$CURRENT_COMMIT" ]
then
	echo "inform \"New commit: $NEW_COMMIT\" 4 4 1" > $FIFO
	log_info "  Upgraded to commit $NEW_COMMIT  Latest changes: $COMMIT_SUBJECT"
	if [ "$NEW_VERSION" != "$CURRENT_VERSION" ]
	then
		echo "inform \"New version: $NEW_VERSION - need restart/reload.\" 5 4 1" > $FIFO
		log_info "  Upgrade from $CURRENT_VERSION to $NEW_VERSION"

		if ! fgrep -q $NEW_VERSION $WWW_CONFIG
		then
			CMD="/VERSION/c\	define\(\"VERSION\", \"$NEW_VERSION\"\);"
			sed -i "$CMD" $WWW_CONFIG
		fi
	else
		echo "inform \"Version is unchanged - recommend reload.\" 5 4 1" > $FIFO
		log_info "  Version number is unchanged." >> $LOG_FILE
	fi
	echo "inform \"Latest changes:\" 6 4 1" > $FIFO
	echo "inform \"$COMMIT_SUBJECT\" 7 4 1" > $FIFO
	TIMEOUT=20
else
	echo "inform \"No new upgrade is available.\" 4 4 1" > $FIFO
	log_info "  No upgrade is available."
	if [ "$NEW_VERSION" == "$CURRENT_VERSION" ]
	then
		echo "inform \"PiKrellCam is already up to date.\" 5 4 1" > $FIFO
		TIMEOUT=6
	else
		echo "inform \"But the latest version is not running.\" 5 4 1" > $FIFO
		echo "inform \"Did you restart after the last upgrade?\" 6 4 1" > $FIFO
		TIMEOUT=10
	fi
fi

MESSAGE=`$INSTALL_DIR/scripts-dist/_upgrade-message`
len=${#MESSAGE}
if (( len > 0 ))
then
	echo "inform \"$MESSAGE\" 8 4 1" > $FIFO
	TIMEOUT=20
fi

echo "inform timeout $TIMEOUT" > $FIFO
